### ISSUE TITLE
Failed to create CloudWatch entities due to missing log group

### ISSUE THREAD

**Issue by brian-petersen** [slimwizard/venmo-request-lambda#2]
When first applying the terraform code, the CloudWatch metrics and alarm failed to be created because the log group does not yet exist. I had to manually trigger the created Lambda function so the log group got created and rerun the terraform code to finish creating all CloudWatch entities that depend on the log group existing.

**Comment by slimwizard** [comment]
Thanks for pointing this out. I was adding things iteratively and must have incorporated the CW metric/alarm objects after I had already created and tested the Lambda function. I've updated lambda.tf and alarm.tf to explicitly create the log group and ensure it exists before the CW metric filter is added. Tested from a clean environment and everything is being created as expected.
